formatter: "markdown table"

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: name

sections:
  show:
    - requirements
    - providers
    - resources
    - inputs
    - outputs

settings:
  anchor: true
  default: true
  description: true
  required: true
  sensitive: true
  type: true
